language: node_js
node_js:
  - "7.1.0"
env:
  - CXX=g++-4.8
before_install:
  - "sudo apt-get install libavahi-compat-libdnssd-dev"
  - "mkdir ~/.homebridge"
  - "echo '{ \n
    \"bridge\": { \n
      \"name\": \"Test-Bridge\", \n
      \"username\": \"CC:22:3D:E3:CE:31\", \n
      \"port\": 51826, \n
      \"pin\": \"130-61-401\" \n
    }, \n
    \"platforms\": [ \n
      { \n
      \"platform\": \"Server\", \n
      \"port\": 8765, \n
      \"name\": \"Homebridge Server\" \n
      } \n
    ], \n
    \"accessories\": [] \n
    }' > ~/.homebridge/config.json"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
